# Generated by Django 2.1.3 on 2018-11-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('hembra', 'Hembra'), ('macho', 'Macho')], max_length=15),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='refugio.Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(choices=[('perros', 'Perros'), ('gatos', 'Gatos'), ('otros', 'Otros')], max_length=50),
        ),
    ]
