# Generated by Django 2.1.3 on 2018-11-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0003_auto_20181124_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='mascota_a_adoptar',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
